tape_web:
  image:  daocloud.io/kitsudo/django-server
  container_name: tape_web
  volumes:
    - ./:/app/server/
  working_dir: /app/server
  entrypoint: ./centos_start.sh
  environment:
    - VIRTUAL_HOST=web.tapecloud.cc
    - VIRTUAL_PORT=8080
  ports:
    - "8080"
  external_links:
    - mysql5:mysql
    - memcached